feat: 로그인 관심사 분리
The-Fellowship-of-the-matzip/mat.zip-back pull request #10
Opened 2022-06-09 13:04 UTC by jayjaehunchoi

## issue: #9 

## as-is
- 로그인 로직 처리를 비즈니스 로직에서 실행한다.

## to-be
- 로그인 인터셉터를 구현한다.
- AuthContext를 생성한다.
- ArgumentResolver로 **githunId**값을 반환받는다.

인터셉터에 pattern 등록해서 사용하시면 됩니다.
Token의 Subject는 githubId입니다. 이 값 기반으로 Member정보를 찾아오면 됩니다.

에러관련해서, InternalException과 BadRequestException 등 RuntimeException을 상속받는 클래스를 만들어 이를 기준으로 예외를 구분하면 어떨까합니다. 혹은 에러 코드와 에러 메시지를 보관하는 enum 클래스를 만들어도 되구요.. 예외 핸들링 관련해서 이야기를 더 나눠봐야 할 것 같아요

2022-06-10 01:43 UTC, jinyoungchoi95 requested changes
빠르게 잘 구현해주셨네요 👍 

간단하게(?) 의견남겨두었어요 :) 확인하시고 멘션주세요~~

2022-06-10 01:43 UTC, jinyoungchoi95 commented on src/main/java/com/woowacourse/auth/config/AuthConfig.java
> +    }
제 기억에는 지금 로그인이 필요한 서비스는 `리뷰 남기기` 기능밖에 없다고 생각하는데요.
그렇다면 지금은 interceptor를 `/api/campus/{campusId}/reviews`에 대해서만 남겨도 되지 않을까요?

2022-06-10 01:43 UTC, jinyoungchoi95 commented on src/main/java/com/woowacourse/auth/presentation/AuthenticationArgumentResolver.java
> +        return authenticationContext.getAuthority();
네이밍에 관련해서 이야기할까하는데요.
보통 인증/인가에서는 네이밍을
- `Principal` : 사용자 식별 정보
- `Credential` : 사용자 민감 정보
- `Authority` : 사용자 인가 정보

를 가져가는데, 현재는 `Principal`에 더 가깝다는 생각이 드는데 어떻게 생각하세요?

2022-06-10 01:43 UTC, jinyoungchoi95 commented on src/main/java/com/woowacourse/auth/presentation/AuthenticationContext.java
> +    }
👍

2022-06-10 01:43 UTC, jinyoungchoi95 commented on src/main/java/com/woowacourse/auth/presentation/LoginInterceptor.java
> +        return HttpMethod.OPTIONS.matches(request.getMethod());
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/cors/CorsUtils.html

요런 api도 있으니 확인해보시면 좋을 것 같아요 :)

2022-06-10 01:43 UTC, jinyoungchoi95 commented on src/main/java/com/woowacourse/auth/presentation/LoginInterceptor.java
> +        throw new InvalidTokenException();
이거 전에 말씀드린다고 했던 내용인데요 :)
`validationToken()`과 `getPayload()`는 둘다 jjwt의 resolving 메소드를 써요. 그럼 두 동작이 결국 boolean을 반환하느냐 payload를 반환하느냐의 차이일뿐 로직이 같다는 거죠.

그렇다면 동일한 두 로직이 똑같이 진행된다라는 생각이 드시지 않나요?

`getPayload()`에서 `JwtException`이 발생했을 때 `throw new InvalidTokenException();`를 해주면 아래와 같이 수정될 수도 있다라는 생각인데 어떻게 생각하세요?

```suggestion
        authenticationContext.setAuthority(jwtTokenProvider.getPayload(token));
        return true;
```

2022-06-10 16:50 UTC, Ohzzi approved these changes
잘 구현해주셔서 크게 리뷰드릴 부분 자체는 없는 것 같아요! :)
오리가 의견 남겨주신 부분은 저도 오리 의견에 동의합니다!
`preflight` 관련 부분에만 제 의견 하나 남겨뒀어요~

2022-06-10 16:50 UTC, Ohzzi commented on src/main/java/com/woowacourse/auth/presentation/LoginInterceptor.java
> +        return HttpMethod.OPTIONS.matches(request.getMethod());
오리가 보내준 api를 사용할거라면 사용해도 괜찮을 것 같고, 만약 api 없이 preflight만 잡으려면 추가로 preflight 관련 헤더까지 체크하는게 좋을 것 같아요!

2022-06-10 16:50 UTC, Ohzzi commented on src/main/java/com/woowacourse/auth/presentation/AuthenticationContext.java
> +
이렇게도 만들어서 쓸 수 있군요 👍

2022-06-10 16:50 UTC, Ohzzi commented on src/main/java/com/woowacourse/auth/presentation/LoginInterceptor.java
> +        throw new InvalidTokenException();
동감합니다. `getClaimJws` 메서드까지 줄일 수 있을 것 같아요

2022-06-11 02:52 UTC, jinyoungchoi95 approved these changes
반영 다 잘 되어서 어프루브 하겠습니다~

2022-06-11 02:53 UTC, merged