feat: 이미지 url 추가 및 조회
The-Fellowship-of-the-matzip/mat.zip-back pull request #141
Opened 2023-05-16 13:46 UTC by kevstevie

## issue: #140

## as-is
- 댓글에 이미지를 넣을 수 없다.

## to-be
- `GET /api/restaurants/{restaurantId}/reviews`
    - ReviewResponse 내에 이미지 url 추가
- `POST /api/restaurants/{restaurantId}/reviews`
    - ReviewCreateRequest 내에 이미지 url 추가

2023-05-16 13:50 UTC, jayjaehunchoi approved these changes
근데 이거 요런식으로 imageUrl을 단다는 것은, 댓글에 이미지를 업로드하면 자동으로 s3에 업로드 -> 이미지 url 생성 요런 느낌으로 진행한다는 것인가여?

2023-05-16 13:50 UTC, jayjaehunchoi commented on matzip-core/src/main/java/com/woowacourse/matzip/domain/review/Review.java
>          registerEvent(new ReviewCreatedEvent(restaurantId, rating));
아 여기서 이벤트 발행하고 있었었네 ㅋ

2023-05-25 06:15 UTC, beer-2000 requested changes
구현하신 코드 잘 확인했습니다!
벌써 피쳐 하나 구현하시다니 대단하시네요.

- imageUrl 길이 문제 없는지 체크
- 실행 후 테스트

위 두 가지 항목 체크 후 배포하면 어떨까 싶어 Request changes 남깁니다.
고생하셨습니다!

2023-05-25 06:15 UTC, beer-2000 commented on matzip-app-external-api/src/test/resources/schema.sql
> +    image_url     varchar(255) NULL,
255자로 길이 충분할까요?
https://docs.aws.amazon.com/ko_kr/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorS3Origin.html#RequestS3MaxRequestStringLength
위의 AWS 문서 보니, 255자를 넘을 수도 있을 것 같아 말씀드려봅니다.

2023-05-25 06:15 UTC, beer-2000 commented on matzip-core/src/main/java/com/woowacourse/matzip/domain/image/Image.java
> +@Entity
주드 JPA 폼 미쳤네요

2023-05-25 06:15 UTC, beer-2000 requested changes
구현하신 코드 잘 확인했습니다!
벌써 피쳐 하나 구현하시다니 대단하시네요.

- imageUrl 길이 문제 없는지 체크
- 실행 후 테스트

위 두 가지 항목 체크 후 배포하면 어떨까 싶어 Request changes 남깁니다.
고생하셨습니다!

2023-05-25 06:15 UTC, beer-2000 requested changes
구현하신 코드 잘 확인했습니다!
벌써 피쳐 하나 구현하시다니 대단하시네요.

- imageUrl 길이 문제 없는지 체크
- 실행 후 테스트

위 두 가지 항목 체크 후 배포하면 어떨까 싶어 Request changes 남깁니다.
고생하셨습니다!

2023-06-02 09:04 UTC, kevstevie commented on matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/support/ImageUploader.java
> +        return !contentType.contains(IMAGE);
검증 과정을 이렇게 생각했는데 사실 contentType은 MultiPart뭐시기라서 절대 통과하지 못하더군요
original name의 확장자를 검증한다던가 하는 방식은 어떨까요

2023-06-04 12:26 UTC, jinyoungchoi95 requested changes
리뷰가 늦었네요 😢 코멘트 확인부탁드려요~

2023-06-04 12:26 UTC, jinyoungchoi95 commented on matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/support/ImageUploader.java
> +        return !contentType.contains(IMAGE);
네 좋아요! `image/jpg` 형태로 media type이 나오는줄 알았는데 그게 아니었군요 🤔

2023-06-04 12:26 UTC, jinyoungchoi95 commented on matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/support/ImageUploader.java
> +                            .withCannedAcl(CannedAccessControlList.PublicRead)
이 옵션을 추가하신 이유가 있을까요?

2023-06-05 05:46 UTC, kevstevie commented on matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/support/ImageUploader.java
> +                            .withCannedAcl(CannedAccessControlList.PublicRead)
어떤 권한이 적절할지 찾아보겠습니다..

2023-06-05 05:47 UTC, kevstevie commented on matzip-app-external-api/src/main/resources/application.yml
> +      auto: false
CloudFormation이 어쩌구 나오는데 더 찾아보고 반영하겠습니다..

2023-06-11 08:09 UTC, kevstevie commented on matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/support/ImageUploader.java
> +                            .withCannedAcl(CannedAccessControlList.PublicRead)
PublicRead 권한으로 업로드해야 url을 통한 조회가 가능한 것 같습니다

2023-06-11 08:16 UTC, kevstevie commented on matzip-app-external-api/src/test/resources/schema.sql
> +    image_url     varchar(255) NULL,
이부분이 문제가 되면 추후에 image 객체 수정해야겠네요

2023-06-11 08:32 UTC, kevstevie commented
이거 영 맘에 안드는데 나중에 https://docs.aws.amazon.com/sdk-for-java/index.html 이 라이브러리로 리팩터링해보겠습니다..

2023-06-15 13:12 UTC, beer-2000 approved these changes

2023-06-22 05:11 UTC, closed without merging