feat: 리뷰 작성자의 리뷰 개수 표시 기능
The-Fellowship-of-the-matzip/mat.zip-back pull request #153
Opened 2023-05-30 11:56 UTC by kevstevie

## issue: #151

## as-is
- 리뷰 작성자의 리뷰 개수가 표시되지 않는다

## to-be
- 리뷰 작성자의 리뷰 개수를 표시한다

2023-06-01 13:16 UTC, jinyoungchoi95 approved these changes

2023-06-03 14:23 UTC, Cyma-s approved these changes

2023-06-11 10:38 UTC, kevstevie commented
쿼리가 한번만 나가는 쪽으로 수정했는데 이 방식의 코드에 문제가 없다면?
아마 평균 구하는 것도 같은 메서드에 컬럼 하나만 더하는 걸로 진행할 것 같습니다

2023-06-13 07:11 UTC, Cyma-s requested changes
이런 데이터가 들어오지는 않을 것 같은데 그래도 테스트 추가하면 좋을 것 같아서 리뷰 남겼습니다 확인해주세요

2023-06-13 07:11 UTC, Cyma-s commented on matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/ReviewService.java
> +        return ReviewResponse.of(review, review.isWriter(githubId), reviewCountByMemberIds.getOrDefault(review.getMember().getId(), ZERO_REVIEW));
`getOrDefault` 👍

2023-06-13 07:11 UTC, Cyma-s commented on matzip-core/src/test/java/com/woowacourse/matzip/domain/review/ReviewRepositoryTest.java
> +        var reviewCountByMemberIds = reviewRepository.countReviewsByMemberIds(List.of(member.getId(), member2.getId()));
member1이나 member2 중에 리뷰가 없는 member가 포함될 때도 문제 없나요?

2023-06-13 07:11 UTC, Cyma-s commented on matzip-core/src/test/java/com/woowacourse/matzip/domain/review/ReviewRepositoryTest.java
> +        var reviewCountByMemberIds = reviewRepository.countReviewsByMemberIds(List.of(member.getId(), member2.getId()));
`countReviewsByMemberIds`의 인자로 빈 리스트가 주어지는 경우도 테스트해보면 좋을 것 같아요

2023-06-13 13:11 UTC, beer-2000 approved these changes
베로가 짚어주신 부분 외에 다른 의견은 없는 것 같아 Approve 하겠습니다.
고생하셨습니다!

2023-06-13 13:11 UTC, beer-2000 commented on matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/response/ReviewResponse.java
> +        public static ReviewAuthor of(final Member member, final Long reviewCount) {
컨벤션 적용 너무 좋네염

2023-06-16 08:18 UTC, Cyma-s approved these changes

2023-06-16 08:20 UTC, kevstevie commented on matzip-core/src/test/java/com/woowacourse/matzip/domain/review/ReviewRepositoryTest.java
> +        for (int i = 1; i <= 10; i++) {
사용하는 픽스쳐가 있긴 하던데 일단 만들고 생각할까요

2023-06-16 08:28 UTC, merged