feat: prod application.yml submodule로 분리
The-Fellowship-of-the-matzip/mat.zip-back pull request #154
Opened 2023-06-02 05:19 UTC by Cyma-s

## issue: #144 

## as-is
- production 환경의 application.yml 파일을 서버에서 관리하여 prod 설정을 local에서 알 수 없다.

## to-be
- production 환경의 application.yml 파일을 서브 모듈로 관리한다.

2023-06-02 06:41 UTC, jinyoungchoi95 requested changes
readme에 submodule 최초 적용하는 방법이랑 업데이트된버전 적용하는 방법 명령어 정리해주시면 좋을 것 같아요!

겸사겸사 5기분들의 readme도 같이....😊

2023-06-02 06:41 UTC, jinyoungchoi95 requested changes
readme에 submodule 최초 적용하는 방법이랑 업데이트된버전 적용하는 방법 명령어 정리해주시면 좋을 것 같아요!

겸사겸사 5기분들의 readme도 같이....😊

2023-06-03 16:27 UTC, jinyoungchoi95 approved these changes

2023-06-03 16:56 UTC, kevstevie commented on README.md
> +| ![](https://github.com/Cyma-s.png?size=200) | ![](https://github.com/beer-2000.png?size=200) | ![](https://github.com/kevstevie.png?size=200) |
프사 달았습니다..

2023-06-04 03:54 UTC, Cyma-s commented on README.md
> +| ![](https://github.com/Cyma-s.png?size=200) | ![](https://github.com/beer-2000.png?size=200) | ![](https://github.com/kevstevie.png?size=200) |
주드 프사는 귀하네요 ㄷㄷ

2023-06-06 04:58 UTC, merged