feat: 식당 목록 조회시 각 식당의 리뷰 개수 반환
The-Fellowship-of-the-matzip/mat.zip-back pull request #156
Opened 2023-06-04 10:52 UTC by kevstevie

## issue: #155

## as-is

- 식당 목록 조회 시 식당에 대한 정보가 적음

## to-be

- 목록에서 리뷰의 개수를 확인할 수 있게 함

2023-06-04 12:37 UTC, jinyoungchoi95 approved these changes

2023-06-04 12:38 UTC, jinyoungchoi95 requested changes

2023-06-04 12:38 UTC, jinyoungchoi95 commented on matzip-app-external-api/src/test/java/com/woowacourse/matzip/application/RestaurantServiceTest.java
> +        assertThat(restaurantTitleResponse.getReviewCount()).isEqualTo(0);
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&pullRequest=156&id=The-Fellowship-of-the-matzip_mat.zip-back&open=AYiGDi2bCAaW0YntNneo

라고 하네요 :)

2023-06-05 14:09 UTC, jinyoungchoi95 approved these changes

2023-06-06 02:13 UTC, Cyma-s approved these changes

2023-06-11 08:11 UTC, merged