feat: 리뷰 조회시 작성자의 평균 별점 조회
The-Fellowship-of-the-matzip/mat.zip-back pull request #164
Opened 2023-06-16 09:02 UTC by kevstevie

## issue: #163 

as-is

- 사용자의 별점 평균에 따른 신뢰도 확인이 어려움

to-be

- 사용자의 리뷰 개수를 조회할 때 별점 평균을 함께 조회

기존에 Map으로 변환하던 과정에서 ReviewInfo 일급 컬렉션에서 직접 찾아서 반환하도록 수정
O(1)에서 O(n)이 되었는데 Map을 사용하는것보다 안정적이라고 판단해서 수정했습니다.

2023-06-16 11:15 UTC, beer-2000 approved these changes

2023-06-16 11:18 UTC, beer-2000 approved these changes

2023-06-16 11:18 UTC, beer-2000 commented on matzip-core/src/main/java/com/woowacourse/matzip/domain/review/ReviewInfoByMembers.java
> +public class ReviewInfoByMembers {
네이밍이 직관적이지 않은 것 같은데,
MemberReviewInfo / MemberReviewInfos
MemberReviewInfo / MemberReviewInfoCollection
ReviewInfoByMember / ReviewInfoByMemberCollection
등으로 수정하면 어떨지요?

2023-06-17 02:23 UTC, Cyma-s approved these changes

2023-06-17 02:23 UTC, Cyma-s commented on matzip-core/src/test/java/com/woowacourse/matzip/domain/review/ReviewRepositoryTest.java
> +    @Test
만약 사용자가 리뷰를 작성하지 않았다면 평균 별점이 0으로 잘 나오는지도 테스트 하면 좋을 것 같아요

2023-06-17 07:32 UTC, jinyoungchoi95 requested changes
수고하셨습니다 코멘트 확인해주세요~

2023-06-17 07:32 UTC, jinyoungchoi95 commented on matzip-core/src/main/java/com/woowacourse/matzip/domain/review/ReviewInfoByMembers.java
> +    }
id가 memberId를 비교하는 것 같은데 `findByMemberId`가 조금 더 명확할 것 같네요.

2023-06-17 07:32 UTC, jinyoungchoi95 commented on matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/ReviewService.java
> +        );
```java
List<Long> memberIds = getMemberIds(page);
ReviewInfoByMembers reviewInfoByMembers = new ReviewInfoByMembers(
        reviewRepository.findMemberReviewInfosByMemberIds(memberIds)
);
```
는 리뷰에서 유저들의 ids를 다 가져와서 해당 유저의 정보를 반환하는 것으로 보이는데요. 메소드로 분리되면 좋을 것 같네요

2023-06-18 03:53 UTC, kevstevie commented on matzip-core/src/test/java/com/woowacourse/matzip/domain/review/ReviewRepositoryTest.java
> +    @Test
음 group by를 쿼리를 통해 가져오는 형태라 반환 collection이 empty라는 것을 통해 검증하도록 햇습니다

2023-06-18 03:54 UTC, kevstevie commented on matzip-core/src/main/java/com/woowacourse/matzip/domain/review/ReviewInfoByMembers.java
> +public class ReviewInfoByMembers {
Review 정보에 대한 클래스라서  MemberReviewInfo와 고민 중에 ReviewInfo를 앞에 두는 쪽으로 결정했던건데 어느게 나을까요

2023-06-18 04:38 UTC, beer-2000 commented on matzip-core/src/main/java/com/woowacourse/matzip/domain/review/ReviewInfoByMembers.java
> +public class ReviewInfoByMembers {
어렵네용 ㅋㅋㅋ .. ReviewInfosByMember가 저는 더 알맞아보인다고 생각은 하나..
(지금은 Members에 대해 찾은 ReviewInfo라고 느껴져서)
주드의 판단에 맡기겠습니당!

2023-06-25 14:22 UTC, jinyoungchoi95 approved these changes
수고하셨습니다~

2023-06-26 11:07 UTC, merged