feat: 북마크(나의 맛집) API 구현 & 북마크 정보 표시
The-Fellowship-of-the-matzip/mat.zip-back pull request #165
Opened 2023-06-16 14:58 UTC by beer-2000

## issue: #160 
close #160 

## as-is
- 북마크 정보를 저장할 수 없었다.
- 식당 정보 조회 시, 북마크 정보를 볼 수 없다.

## to-be
- 북마크 정보를 저장, 삭제할 수 있다.
- 식당 정보 조회 시, 북마크 정보를 볼 수 있다.

식당 정보 조회 시 북마크 여부를 포함하기 위해,
`RestaurantController`의 모든 메서드가 `loginOrNotInterceptor`를 거치도록 구현했습니다.

그렇지 않고 `RestaurantService`가 `AuthenticationContext`를 사용하는 방식으로도 구현이 가능하나,
멀티 스레드 환경에서 `Service`가 Request scope bean을 의존하는 것에서 동시성 문제가 발생할 수도 있다고 판단했습니다.

감사합니다.

2023-06-17 03:12 UTC, Ohzzi requested changes
리뷰 하다가 도메인 로직 자체의 오류를 발견했어요. 시간이 조금 걸리겠지만 천천히 시간을 가지고 수정해보아요!

지금 구조는 `@OneToMany` 매핑을 사용한 뒤 Member 1 : N Restaurant 라는 구조를 만들고 "북마크" 라고 이야기 하고 있어요. 하지만 체인저가 의도한 구조는 Member N : N Restaurant 여야겠죠? `신동궁감자탕`에 대해 체인저도 베로도 주드도 모두 북마크를 등록할 수 있어야 하니까요.

이런 오류가 발생한 것은, 우리가 객체 관점에서 볼 때는 체인저 라는 멤버 객체에도 신동궁을, 베로라는 멤버 객체에도 신동궁을 넣어주면 북마크로 등록되기 때문이라고 생각해서인 것 같아요(추측해보자면 ㅎ.ㅎ) 하지만 데이터베이스의 관점으로 보자면 오류를 발견할 수 있어요. 아시다시피 RDB는 multiple한 값을 가지는 컬럼을 지원하지 않습니다. 때문에 만약 member 테이블과 restaurant 테이블을 `@OneToMany`로 연관관계를 맺어주면, 실제로는 restaurant 테이블에 `member_id` 라는 외래 키 컬럼이 생길거에요. 그러면 어떻게 되냐면, 체인저에게 북마크로 신동궁이라는 식당을 할당해주면 신동궁에 해당하는 row의 member_id에 체인저의 id가 들어갈거에요. 그런데, 이 상황에서 주드에게 같은 식당에 대한 북마크를 설정해주면 어떨까요? 신동궁에 해당하는 row의 member_id가 주드의 id로 업데이트됩니다. 때문에 체인저 - 신동궁의 연관관계는 없어지게 되는거에요.

이런 문제를 해결하려면, 일대다(다대일) 매핑을 하는 것이 아닌 다대다(N : N) 매핑을 해주어야 해요. JPA에서는 `@ManyToMany`를 통해서 가능합니다. 하지만, `@ManyToMany`는 여러 이유로 사용을 지양해야 해요(지양해야 하는 이유는 나중에 설명드릴게요) 때문에 어떤 대안을 만드냐 하면, 중간 과정을 매핑하는 도메인을 하나 더 만듭니다. 여기서는 북마크가 되겠죠? 그러면

```java
public class BookMark {
    private Long id;
    @ManyToOne
    private Restaurant restaurant;
    ...
}
```
(코드는 진짜 간단하게 짠거고 원래 더 많은 어노테이션으로 잡아줘야 해요)
요런 식으로 북마크라는 중간 도메인을 만들어줄 수 있겠죠? 이러면 멤버가 북마크를 여러 개 가지고 있으면 되는거니까요. 즉, 멤버 하나와 식당 하나를 매핑해주는 테이블을 하나 만들고 이걸 북마크라는 도메인으로 사용하자는 이야기입니다!

2023-06-17 03:12 UTC, Ohzzi commented on matzip-core/src/main/java/com/woowacourse/matzip/domain/member/Member.java
> +
생각해보기) 북마크라는 필드에 `new ArrayList<>();` 로 필드 단에서의 초기화를 해줬는데요, 빌더에도 먹힐까요?

2023-06-18 16:06 UTC, beer-2000 commented on matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/BookmarkService.java
> +        memberRepository.save(member);
아하 처음 알았네요 감사합니다!!

2023-06-18 16:17 UTC, beer-2000 commented on matzip-app-external-api/src/main/java/com/woowacourse/matzip/presentation/BookmarkController.java
> +@RequestMapping("/api/restaurants/{restaurantId}/bookmarks")
생각해보았는데요,
DB의 `bookmark` 기준으로 다대일 관계이나, 리소스 기준으로는 계층형으로 표현할 수 없는 관계라고 생각했습니다.

하지만 `bookmarks`라는 리소스에 대해 POST 메서드를 실행하는 것이고, 부가 정보로서 `restaurants`의 `{restaurantId}`로 특정되는 리소스를 사용할 것이다라고 명시하기 위해
`api/bookmarks/restaurants/{restaurantId}` 순서로 엔드포인트를 수정했습니다.

2023-06-18 16:22 UTC, beer-2000 commented on matzip-core/src/main/java/com/woowacourse/matzip/domain/member/Member.java
> +        throw new BookmarkNotFoundException();
기대하는 동작을 중심으로 로직을 작성한다고 생각하면, 말씀해주신 후자의 방식이 적절해보이네요!

연관관계를 수정하고 `Bookmark`라는 도메인을 추가하면서,
존재하지 않는 북마크를 삭제하는 경우에 별다른 예외를 발생시키지 않고
북마크 삭제에 성공했을 때와 마찬가지로 `204 Status code`를 응답하도록 수정했습니다.

정상 상태라면 존재하지 않는 북마크를 존재한다고 알려주고, 그것을 삭제하는 요청을 받지 않을테고,
삭제 대상이 존재하는지를 클라이언트가 몰라도 된다고 생각했기 때문입니다.
혹시 잘못된 생각이라면 지적 부탁드립니다!

2023-06-18 16:22 UTC, beer-2000 commented on matzip-core/src/main/java/com/woowacourse/matzip/domain/member/Member.java
> +        return false;
오 그렇네요 왜 저렇게 구현했는지 모르겠네요 ㅋㅋ 감사합니다.
해당 로직은 `Bookmark` 도메인 구현하면서 제거되었습니다.

2023-06-18 16:28 UTC, beer-2000 commented on matzip-core/src/main/java/com/woowacourse/matzip/domain/member/Member.java
> +
생각해보기인데 생각만으로는 잘 모르겠어서 (+ `@Builder` 어노테이션이 어떻게 동작하는지 내부를 확인하는 법을 모르겠네용..)
검색해보니 초기값 지정 안해주면 `null`로 생성한다네요..!
초기값 지정할 수 있도록 해당 필드(`bookmarks`)에 `@Builder.Default` 어노테이션 추가했습니다.

2023-06-18 16:38 UTC, beer-2000 commented
@Ohzzi 
적어주신 리뷰 기반으로 리팩터링해보았습니다!
아래에 변경사항과 발생한 문제에 대해 적어보았습니다.

편하실 때 확인 부탁드립니다 😊

### What's changed
- 다대다 관계(Member <-> Restaurant)의 중간 매핑을 위한 Bookmark 도메인 구현
    - Member, Restaurant 모두 Bookmark와 양방향 연결 (Lazy loading 적용)
        - 이유 :
            - Member를 기준으로 Bookmark 조회하는 쿼리가 존재
            - Bookmark를 Restaurant로 변환하는 로직 존재
- 기타 자잘한 수정

### Problem
- RestaurantServiceTest에 존재하던 `북마크_된_식당목록을_반환한다()` 테스트 메서드가 동작하지 않아 삭제했습니다.
    - 테스트 메서드 내부에서 북마크가 정상적으로 저장된 후, Member.getBookmarks() 로 List<Bookmark>를 불러오면 요소 수가 0입니다.
    - 아래에 해당 테스트 메서드 코드를 첨부합니다.

```java
@Transactional
@Rollback(value = false)
@Test
void 북마크_된_식당목록을_반환한다() {
    Restaurant restaurant1 = restaurantRepository.findAll().get(0);
    Restaurant restaurant2 = restaurantRepository.findAll().get(1);

    Member member = Member.builder()
            .githubId("githubId")
            .username("username")
            .profileImage("image.com")
            .build();
    memberRepository.save(member);

    Member savedMember = memberRepository.findById(member.getId()).get();

    Bookmark bookmark1 = Bookmark.builder()
            .id(1L)
            .member(savedMember)
            .restaurant(restaurant1)
            .build();
    bookmarkRepository.save(bookmark1);

    Bookmark bookmark2 = Bookmark.builder()
            .id(2L)
            .member(savedMember)
            .restaurant(restaurant2)
            .build();
    bookmarkRepository.save(bookmark2);

    // 디버깅을 위한 출력
    Bookmark savedBookmark1 = bookmarkRepository.findById(1L).get();
    System.out.println(savedBookmark1.getId()); // 1 출력
    System.out.println(savedBookmark1.getMember().getId()); // 1 출력
    System.out.println("savedMember Bookmarks size : " + savedMember.getBookmarks().size()); // --> 문제의 지점 : 0 출력 (정상적인 상황이라면 2가 출력되어야 합니다.)

    // 아래 호출 메서드(findBookmarkedRestaurants()) 내부에서 member.getBookmarks를 사용하고, 반환값이 빈 리스트라 테스트를 통과하지 못합니다.
    List<RestaurantTitleResponse> responses = restaurantService.findBookmarkedRestaurants("test_github_id");
    assertThat(responses).hasSize(2)
            .extracting("id")
            .containsExactly(1L, 2L);
}
```

2023-06-19 05:05 UTC, Ohzzi commented
체인저가 말해주신 테스트 실패하는 문제의 이유를 알 것 같아요! 이건 연관관계 편의 메서드가 없기 때문인데요, 지금 코드에서 Bookmark에는 Member가 들어가있지만 Member 안에는 Bookmark가 없습니다. (왜냐면 양방향인데 Member의 북마크 필드 안에 Bookmark를 안넣어줬으니까요) 따라서 객체간의 연관관계는 한 방향으로만 있는거죠. 

때문에 bookmark1의 getMember를 하면 savedMember가 나오지만 `savedMember.getBookmarks().size()` 해주면,  savedMember의 북마크 사이즈가 0으로 나오게 되는겁니다.

연관관계 편의 메서드에 대해서는 [이 글](https://velog.io/@ohzzi/JPA-%EC%8A%A4%ED%84%B0%EB%94%94-2-%EC%97%94%ED%8B%B0%ED%8B%B0-%EB%A7%A4%ED%95%91-%EC%97%B0%EA%B4%80%EA%B4%80%EA%B3%84-%EB%A7%A4%ED%95%91-%EA%B8%B0%EC%B4%88) 맨 아래쪽을 참조해주세요!

혹시 이해 안가면 질문주세요!

2023-06-19 11:38 UTC, beer-2000 commented
> 체인저가 말해주신 테스트 실패하는 문제의 이유를 알 것 같아요! 이건 연관관계 편의 메서드가 없기 때문인데요, 지금 코드에서 Bookmark에는 Member가 들어가있지만 Member 안에는 Bookmark가 없습니다. (왜냐면 양방향인데 Member의 북마크 필드 안에 Bookmark를 안넣어줬으니까요) 따라서 객체간의 연관관계는 한 방향으로만 있는거죠.
> 
> 때문에 bookmark1의 getMember를 하면 savedMember가 나오지만 `savedMember.getBookmarks().size()` 해주면, savedMember의 북마크 사이즈가 0으로 나오게 되는겁니다.
> 
> 연관관계 편의 메서드에 대해서는 [이 글](https://velog.io/@ohzzi/JPA-%EC%8A%A4%ED%84%B0%EB%94%94-2-%EC%97%94%ED%8B%B0%ED%8B%B0-%EB%A7%A4%ED%95%91-%EC%97%B0%EA%B4%80%EA%B4%80%EA%B3%84-%EB%A7%A4%ED%95%91-%EA%B8%B0%EC%B4%88) 맨 아래쪽을 참조해주세요!
> 
> 혹시 이해 안가면 질문주세요!

아하.. 공유해주신 아티클 보고 이해했습니다..!
그런데..

서버를 실행하면 왜 의도한대로 동작할까요?
![image](https://github.com/The-Fellowship-of-the-matzip/mat.zip-back/assets/97939198/6a23d99d-67ab-4031-ae2b-221b1b3afb72)

위의 사진의 `findBookmaredRestaurants()` 메서드는 북마크된 식당 조회 API 호출 시 사용되는 메서드로,
`member.getBookmarks()` 로 `bookmarks` 필드(`List<Bookmark>`)를 `List<RestaurantTitleResponse>`로 매핑하는데요,
의도한대로 `Bookmark` 객체들이 불러와집니다.


그런데 테스트 코드에서는, `Member`를 `Repository`를 통해 다시 불러와서 테스트해보아도
`getBookmarks()`가 빈 리스트를 반환합니다.


정리해서 두 가지 질문을 남깁니다..!
Q1. 테스트에서는 연관관계 편의 메서드가 없어 조회가 되지 않는 `Member`의 `bookmarks` 필드가, 프로덕션 코드에서는 의도한 대로 조회되는 이유가 뭘까요..?
Q2. `Member`의 `bookmarks`를 그대로 조회하는 쿼리를 사용하기에 양방향으로 연결했는데, 이런 상황에서도 `Bookmark`에서만 단방향으로 `Member`를 참조하고, 특정 `Member`의 `Bookmark`들을 조회할 때는 WHERE 절로 `member_id` 값을 통해 조회하는 것이 더 나은 선택일까요?

2023-06-25 08:55 UTC, Ohzzi commented
Q1. 테스트에서는 연관관계 편의 메서드가 없어 조회가 되지 않는 Member의 bookmarks 필드가, 프로덕션 코드에서는 의도한 대로 조회되는 이유가 뭘까요..?
A. 이는 영속성 컨텍스트 때문에 그렇습니다. JPA에는 하나의 트랜잭션 당 하나의 영속성 컨텍스트가 유지되는데요, 이 때 영속성 컨텍스트는 조회하는 객체의 **동일성**을 보장해줍니다. 즉 반드시 주소가 같은 객체가 나온다는 것이죠. 때문에 테스트 코드에서는 연관관계가 한쪽으로만 유지되어 있는 객체가 계속해서 나오게 되고, getBookmarks를 했을 때 빈 북마크가 나오게 됩니다.
하지만 API 호출을 통해서 테스트해보면 다르죠. 북마크를 넣어주는 트랜잭션과, 북마크를 조회하는 트랜잭션은 다릅니다. 따라서 영속성 컨텍스트의 동일성 보장과 아무 관계 없이 각각의 API 호출에 따라 다른 객체가 튀어나오게 됩니다. 이 때, 앞서 테스트에서도 북마크 안에는 멤버가 설정되었었죠? 연관관계의 주인인 북마크에 멤버와의 관계를 설정했으므로 데이터베이스 상에 member_id 컬럼 값이 들어가게 되고, 데이터베이스에서 멤버를 꺼내왔을 때 북마크 연관관계를 전부 불러올 수 있게 되는 것입니다.

Q2. Member의 bookmarks를 그대로 조회하는 쿼리를 사용할 필요가 있어서 양방향으로 연결했는데,
이런 상황에서도 Bookmark에서만 단방향으로 Member를 참조하고,
특정 Member의 Bookmark들을 조회할 때는 WHERE 절로 member_id 값을 통해 조회하는 것이 더 나은 선택일까요?
A. 이건 정답이 없는 문제 같아요. 여러 방법들을 써보고 장단점을 비교해보는게 좋지 않을까 싶어요. 예를들어 일대다 단방향은 거의 금기라는 의견이 강했었는데, 이에 대해서도 사용해서 큰 문제 될 것이 없다라고 이야기 하시는 분도 많아요. 팀 컨벤션으로 결정하는게 좋을 것 같습니다. 맛집 자체가 연관관계로 해결할 수 있는건 최대한 해결하는 코드들이 많아서, 양방향 연결도 나쁘지는 않을 것 같아요. 단, 식당 -> 북마크 로의 연결은 필요 없으니까 요기만 단방향으로 처리하면 되지 않을까 싶습니다.

2023-06-25 08:56 UTC, Ohzzi approved these changes

2023-06-26 11:26 UTC, beer-2000 commented
@Ohzzi 
아하..! 트랜잭션 하나당 영속성 컨텍스트가 유지되어서 그런 것이었군요..! 완전 이해됐습니다.
현재 지적해주신 문제로 RestaurantServiceTest에 케이스 추가가 어려운데요,
우선 API 테스트 상으로는 문제가 없어
일정 상 먼저 머지하겠습니다.

후에 연관관계 편의 메서드 추가 등을 통해 로직을 개선하고, 테스트 케이스 추가해보겠습니다.
감사합니다!

2023-06-26 11:27 UTC, merged