chore: local phase에서 토큰에 memberId 사용할 수 있도록 수정
The-Fellowship-of-the-matzip/mat.zip-back pull request #166
Opened 2023-06-16 17:35 UTC by beer-2000

## issue: #149 
close #149 

## as-is
- local에서 개발할 때, token을 발급받아 사용해야 한다.

## to-be
- local에서 개발할 때, JWT 대신 Member의 ID를 Token에 넣어 사용한다.
(예시 : `Authorization` 헤더에 `Bearer 1` 삽입)

`@Value("${spring.profiles.active:}")`와 `System.getProperty("spring.profiles.active")`의 값이 null이 되어
Environment bean을 주입받아 사용했습니다. (이유를 잘 모르겠네요.. 더 찾아보겠습니다.)

감사합니다 😊

2023-06-17 06:52 UTC, jinyoungchoi95 requested changes
수고하셨습니다~ 코맨트 확인부탁드려요 :)


추가로 질문주신 부분에서 `@Value("${spring.profiles.active:}")`와 `System.getProperty("spring.profiles.active")` 안되는 부분은 추측을 통해 원인을 파악해보면

application에서 run된 log를 보면 아래와 같은 로그를 볼 수 있어요.
```
The following 3 profiles are active: "local", "web-local", "db-local"
```
active profile이 3개네요. 그럼 application이 뜰 때 해당 properties에 디버깅 포인트를 걸어 들어가보면

<img width="657" alt="스크린샷 2023-06-17 오후 3 49 33" src="https://github.com/The-Fellowship-of-the-matzip/mat.zip-back/assets/69106910/b9415f89-f2dd-48c2-b6a4-3f4e18b6d115">

로 List<String>이 되네요 👀 아마 가져오는 방식에 있어서 타입이 달라서 그렇게 되지 않나라고 생각이 듭니다.

사실 이렇게 가져와서 사용해보지는 않고 스프링에서 제공하는 `@Profile`로도 충분히 해결가능해보이는 이슈로 보여서 아래에서 조금 더 이야기해보도록해요!

2023-06-17 06:52 UTC, jinyoungchoi95 commented on matzip-app-external-api/src/main/java/com/woowacourse/auth/presentation/interceptor/LoginInterceptor.java
> +    @Autowired
불필요해보여요

2023-06-17 06:52 UTC, jinyoungchoi95 commented on matzip-app-external-api/src/main/java/com/woowacourse/auth/presentation/interceptor/LoginInterceptor.java
> +    public LoginInterceptor(Environment environment, final JwtTokenProvider jwtTokenProvider,
```suggestion
    public LoginInterceptor(final Environment environment, final JwtTokenProvider jwtTokenProvider,
```

2023-06-17 06:52 UTC, jinyoungchoi95 commented on matzip-app-external-api/src/main/java/com/woowacourse/auth/presentation/interceptor/LoginInterceptor.java
> +        }
음... 이건 구현 방향성에 대한 이야기를 하면 좋을 것 같은데요.
`@Profile`이 아닌 현재 형태로 구현되어있는 이유가 있는지가 먼저 궁금합니다 :)

2023-06-17 07:16 UTC, beer-2000 commented on matzip-app-external-api/src/main/java/com/woowacourse/auth/presentation/interceptor/LoginInterceptor.java
> +        }
@Profile 어노테이션 사용해서 분기하려했는데,
메서드 레벨에서 해당 어노테이션으로 분기하는 방법을 몰라서 Environment를 사용했습니다.

생각하시는 방법에 대해서 일러주실 수 있을까요?

2023-06-17 07:16 UTC, beer-2000 commented
@jinyoungchoi95 
리스트라서 그랬군요.. 오우 감사합니다.
적어주신 코멘트 확인했고, 질문 남겼은 확인 부탁드립니다.😊

2023-06-17 07:26 UTC, jinyoungchoi95 commented on matzip-app-external-api/src/main/java/com/woowacourse/auth/presentation/interceptor/LoginInterceptor.java
> +        }
음 더 좋은 방법들이 많을 것 같은데 당장 떠오르는 것들은

Bean들을 `@Profile(local) LoginInterceptor` `@Profile(prod) LoginInterceptor`로 분리하여 등록하면 loginInterceptor를 config에서 받아서 등록하면 알아서 분기가 되는 방법이 있을 것 같구요.

근본적으로 Login할 때 인증된 가짜 Token이 필요하다면 `@Profile(local) LocalLoginController`를 생성해보아도 좋을 것 같네요.

2023-06-17 08:29 UTC, beer-2000 commented on matzip-app-external-api/src/main/java/com/woowacourse/auth/presentation/interceptor/LoginInterceptor.java
> +        }
같은 이름의 클래스를 같은 파일에 둘 수가 없는데요,
프로필이 다른 같은 이름의 클래스를 어떻게 배치할 수 있을지요..?

public class 말고 class로 두어 다른 이름의 파일에 두는 것이 좋을지요?

2023-06-18 02:50 UTC, jayjaehunchoi approved these changes
개발 편의성 목적으로 봤을 때 저는 이정도도 크게 문제 없다는 생각이긴 합니당.
오리 의견 참고해서 더 좋은 방식으로 개선해봐도 좋을것 같아유

2023-06-18 04:45 UTC, beer-2000 commented
> 개발 편의성 목적으로 봤을 때 저는 이정도도 크게 문제 없다는 생각이긴 합니당. 오리 의견 참고해서 더 좋은 방식으로 개선해봐도 좋을것 같아유

옙 감사합니다 !

2023-06-18 04:51 UTC, beer-2000 commented
@jinyoungchoi95 
`LoginInterceptor`를 `Interface`로 두고,
local phase에서 사용하는 `LocalLoginInterceptor`와
local이 아닌 phase에서 사용하는 `ProdLoginInterceptor`를 구현했습니다.

`ProdLoginInterceptor`를 prod phase에서만 사용하도록 하니,
테스트가 default phase에서 실행되면서 Bean이 등록되지 않는 문제가 발생했습니다.
따라서 `ProdLoginInterceptor`를 local이 아닌 모든 phase에서 사용하도록 구현했습니다.

확인 부탁드립니다.
감사합니다!

2023-06-20 03:34 UTC, jinyoungchoi95 requested changes
수고하셨습니다.

테스트에서 특정 profile이 설정되지 않아 `default`가 도는 것이 문제라면, yml에서 test profile 환경을 새로 만들고 `@Profile("local", "test")로 관리하는게 더 좋아보여요. `"!local"`로는 자칫 나중에 놓친 profile이나 포함되지 않아야할 것도 포함될 것 같네요.

```java
@Profile(LOCAL, TEST)
@Component
public class LocalLoginInterceptor implements LoginInterceptor {

@Profile(PROD)
@Component
public class ProdLoginInterceptor implements LoginInterceptor {
```

2023-06-20 03:34 UTC, jinyoungchoi95 commented on matzip-app-external-api/src/main/java/com/woowacourse/auth/presentation/interceptor/LocalLoginInterceptor.java
> +@Profile("local")
profile은 `local`, `test`, `prod`, `beta`등등 계속 생겨날 것 같은데 enum으로 관리되면 좋을 것 같네요.

2023-06-20 04:29 UTC, beer-2000 commented
@jinyoungchoi95 
남겨주신 리뷰 반영해보았습니다.

- 스프링 컨텍스트 실행되는 테스트 환경에서는 test profile으로 설정되도록 했습니다.
- Profile을 아래와 같이 구현했는데요,
    - 어노테이션의 속성 값은 컴파일 시점에 상수여야해서, enum을 사용하지 않고 일반 클래스의 상수 필드를 사용했습니다.
```java
public class Profile {
    public static final String LOCAL = "local";
    public static final String PROD = "prod";
    public static final String TEST = "test";
}
```

감사합니다!

2023-06-20 09:39 UTC, jinyoungchoi95 requested changes
수고하셨습니다~ 거의 다 마무리된 것 같네요. 

코멘트 확인 부탁드려요.

2023-06-20 09:39 UTC, jinyoungchoi95 commented on matzip-app-external-api/src/main/java/com/woowacourse/matzip/config/Profile.java
> +public class Profile {
클래스 네이밍이 `ProfileUtil`에 가까워보이고, 다른곳에서도 충분히 쓰일 수 있어보여서 `matzip-support` 모듈에 `environment` 패키지하위에 두고 사용해도 좋을 것 같아요

2023-06-20 09:39 UTC, jinyoungchoi95 commented on matzip-app-external-api/src/test/java/com/woowacourse/matzip/application/ServiceTest.java
> +@SpringServiceTest
위에서 이야기한대로 사용할 필요가 없을 것 같고, 만약 이런 케이스가 온다면 클래스를 두지 않고 `SpringServiceTest` 어노테이션에 @ActiveProfiles(TEST)를 달아주어도 동작할 것 같네요

2023-06-25 09:17 UTC, beer-2000 commented on matzip-app-external-api/src/test/resources/application.yml
> +      on-profile: test
해당 파일에 대해서 적어주신 Suggested change대로 수정했는데요,
@ActiveProfiles(TEST) 을 제거하면 테스트가 깨지네요.
아래는 에러 메시지 일부인데요, 디폴트 프로필로 설정되면서 ApplicationContext가 로드되지 않는 것 같습니다. (디폴트 프로필에 대해서 LoginInterceptor를 생성하지 않으므로)
```
java.lang.IllegalStateException: Failed to load ApplicationContext

	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:98)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:124)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:118)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
```

2023-06-25 09:43 UTC, beer-2000 commented on matzip-app-external-api/src/test/resources/application.yml
> +      on-profile: test
줌으로 알려주신대로 수정완료했습니다!!

기본 방식으로 프로필 적용하니,
어노테이션 없이 테스트가 잘 동작하네요 ㅎㅎ

2023-06-25 09:46 UTC, beer-2000 commented on matzip-app-external-api/src/main/java/com/woowacourse/matzip/config/Profile.java
> +public class Profile {
말씀해주신대로 패키지 구조, 클래스 네이밍 수정했습니다!

2023-06-25 09:47 UTC, beer-2000 commented on matzip-app-external-api/src/test/java/com/woowacourse/matzip/application/ServiceTest.java
> +@SpringServiceTest
넵 해당 클래스 사용할 필요가 없어져서, 삭제했습니다!

2023-06-25 09:48 UTC, beer-2000 commented
@jinyoungchoi95 
리뷰 반영했습니다!

확실히 훨~~~씬 깔끔해져서 뿌듯하네요.. ㅋㅋㅋ
리뷰 감사합니다.

확인 부탁드립니다~!

2023-06-25 09:49 UTC, jinyoungchoi95 approved these changes
수고 많으셨습니다~

2023-06-25 09:54 UTC, merged