Issue140
The-Fellowship-of-the-matzip/mat.zip-back pull request #172
Opened 2023-06-22 05:14 UTC by kevstevie

## issue: #140 

## as
- 댓글에 이미지를 넣을 수 없다.

## to-be

GET /api/restaurants/{restaurantId}/reviews
ReviewResponse 내에 이미지 url 추가

POST /api/restaurants/{restaurantId}/reviews
ReviewCreateRequest 내에 이미지 url 추가

POST /api/images
이미지 업로드
response cloudfront  이미지 url 반환 (예정)

이미지 업로드는 정상적으로 되는 것 확인했고 추후 용량제한이나 cloudfront url 구조 알게되면 response 수정하겠습니다.
기존에 image 엔티티가 있었는데 굳이 필요한 도메인인가 싶어서 삭제한 상태입니다.

2023-06-22 08:34 UTC, Cyma-s requested changes
이미지 다운로드 관련 부분 확인해주세요
response 링크는 전달된대로 변경 부탁드립니다 🥇

2023-06-25 07:12 UTC, Cyma-s approved these changes
추가할 점은 딱히 안 보이는 것 같은데 API rest docs 추가해주세요 ^-^

2023-06-25 08:50 UTC, beer-2000 approved these changes

2023-06-25 08:50 UTC, beer-2000 commented on matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/ImageService.java
> +        String uuid = UUID.randomUUID().toString();
좋네용 UUID

2023-06-25 08:50 UTC, beer-2000 commented on matzip-app-external-api/src/main/java/com/woowacourse/auth/config/AuthConfig.java
> +                .includePathPattern(IMAGE_UPLOAD_PATH, PathMethod.POST);
로그인 필수 지정 좋슴당

2023-06-25 08:50 UTC, beer-2000 commented on matzip-app-external-api/src/test/resources/application.yml
> +cloud:
요거 로컬 phase 로그인 간소화하는 PR(https://github.com/The-Fellowship-of-the-matzip/mat.zip-back/pull/166#pullrequestreview-1487731449)이랑 충돌날 거 같은데,
그때 같이 보시죵!

2023-06-25 12:22 UTC, merged