feat: 식당 조회시 북마크 수량 조회 기능
The-Fellowship-of-the-matzip/mat.zip-back pull request #204
Opened 2024-06-21 08:18 UTC by Arachneee

## issue: #203

## as-is
- 사용자들이 어떤 음식점을 맛집으로 생각하는지 직관적으로 알기 어려움
 
## to-be
- 식당을 조회할 때 북마크 수량을 함께 조회

2024-06-21 14:47 UTC, PgmJun reviewed
테스트까지 잘 구현해주셨네요 백호!
소소한 리뷰 남겼으니 확인부탁드려요:)

2024-06-21 14:47 UTC, PgmJun commented on matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/RestaurantService.java
>      private RestaurantTitlesResponse toRestaurantTitlesResponse(final String githubId, Slice<Restaurant> page) {
백호가 작성하신 코드는 아니지만
여기에 Slice<Restaurant> page 만 final이 안붙어있는 이유가 있을까요??
같이 생각해보면 좋을 것 같네요!

2024-06-21 14:47 UTC, PgmJun commented on matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/RestaurantService.java
> +                .toList();
👍

2024-06-21 14:47 UTC, PgmJun commented on matzip-app-external-api/src/test/java/com/woowacourse/matzip/application/RestaurantServiceTest.java
>                  () -> assertThat(response.isLiked()).isFalse()
usingRecursiveComparison() 검증에서 제외하는 rating, isLiked와 동일하게
bookmarkCount 도 값을 잘 가지고 있는지 따로 검증해주어야하지 않을까요?

2024-06-22 01:56 UTC, Arachneee commented on matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/RestaurantService.java
>      private RestaurantTitlesResponse toRestaurantTitlesResponse(final String githubId, Slice<Restaurant> page) {
전체적으로 final이 누락된 곳이 좀 있는 것 같아요. final을 생성자, public 메소드, private 메소드 등 어떻게 붙일지 컨벤션을 정하는게 좋을 것 같습니다.
저는 개인적으로 final을 꼭 필요한 곳에만 붙이는 것을 선호합니다. 프로젝트의 크기가 그렇게 크지 않고 작업하는 인원도 적어 final을 붙여서 얻을 수 있는 안정성보다 가독성을 얻는 것이 더 좋다고 생각하기 때문입니다.
또한 지금처럼 final이 누락되면 오히려 혼란을 가중시킨다고 생각합니다.

2024-06-22 02:01 UTC, Arachneee commented on matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/RestaurantService.java
> +                .toList();
java17로 전환하면서 `.collect(Collectors.toList());` 가 sonarlint 에 잡혀서 pr요청시 sonarCloud 가 머지 불가 판정을 내렸습니다. 
그래서 변경파일 부분만 `toList()`로 수정을 하긴 했는데 전체적으로 java17 전환 후 생기는 code smell 을 제거할 필요가 있어보입니다.

2024-06-22 02:07 UTC, Arachneee commented on matzip-app-external-api/src/test/java/com/woowacourse/matzip/application/RestaurantServiceTest.java
>                  () -> assertThat(response.isLiked()).isFalse()
꼼꼼한 리뷰 감사합니다.
bookmarkCount 검증을 누락했네요.
추가했습니다.

2024-06-24 15:31 UTC, jinyoungchoi95 requested changes
수고하셨어요~

2024-06-24 15:31 UTC, jinyoungchoi95 commented on matzip-app-external-api/src/test/java/com/woowacourse/matzip/application/RestaurantServiceTest.java
> +        }
```suggestion
        Member member1 = memberRepository.save(createTestMember("githubId1"));
        bookmarkRepository.save(createTestBookmark(member1, restaurant));
        Member member2 = memberRepository.save(createTestMember("githubId2"));
        bookmarkRepository.save(createTestBookmark(member2, restaurant));
        Member member3 = memberRepository.save(createTestMember("githubId3"));
        bookmarkRepository.save(createTestBookmark(member3, restaurant));
```

가능하면 테스트에는 for와 같은 로직보다는 차라리 하드코딩해서 각 값을 넣어주는 것이 좋을 것 같아요.
물론 로직이 단순할 수도 있지만 1~3이라는 로직자체가들어갔다는 것은 그 구문을 이해해야하는 범위가 늘어나 직관적이지 못하고 간단하더라도 오류를 범할 수 있기 때문이에요.

2024-06-24 15:31 UTC, jinyoungchoi95 commented on matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/RestaurantService.java
> +                bookmarkRepository.countByRestaurantId(restaurantId));
```suggestion
                bookmarkRepository.countByRestaurantId(restaurantId)
        );
```

2024-06-25 07:27 UTC, hyeon0208 approved these changes
수고하셨습니다 백호 ~! 😃
간단한 의견 남겨봤으니 확인해주시면 감사하겠습니다 😊

2024-06-25 07:27 UTC, hyeon0208 commented on matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/RestaurantService.java
>      private RestaurantTitlesResponse toRestaurantTitlesResponse(final String githubId, Slice<Restaurant> page) {
저가 수정하는 코드 또한 final 키워드가 누락되어 있는 부분이 많더라구요
저 같은 경우에는 메서드 내부에서 파라미터 값을 재할당하는 경우를 겪지 못해서
final 키워드를 통해 재할당이 되지 않을 것이란걸 명시한다면 하나도 빠짐없이 붙여야 한다는 주의이고
힘들다면 혼란을 야기하지 않기 위해서 안 붙여야 한다 반반 인데
지금 프로젝트에서는 전반적으로 final 키워드가 선언되어 있는 코드들이 많아
지우기 보다는 붙여주는 것으로 컨벤션을 정하는건 어떨지 의견 드립니다 😃

2024-06-25 07:27 UTC, hyeon0208 commented on matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/RestaurantService.java
>                          .orElse(0.0),
기존에 작성되어 있는 코드 같은데
0.0이라는 값이 직관적으로 다가오지 않다고 느껴져
이를 DEFAULT_RATING 같이 상수로 관리하는 건 어떻게 생각하시나요 ?

2024-06-25 07:27 UTC, hyeon0208 commented on matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/response/RestaurantResponse.java
> +    public static RestaurantResponse of(final Restaurant restaurant, final double rating, final boolean liked, final int bookmarkCount) {
꼼꼼 👍🏻

2024-06-25 09:14 UTC, PgmJun commented on matzip-app-external-api/src/test/java/com/woowacourse/matzip/application/RestaurantServiceTest.java
> +        }
호오 확실히 직관적으로 보이네요!

2024-06-25 15:02 UTC, PgmJun commented on matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/RestaurantService.java
> +                .toList();
final 처리와 더불어서 전체적으로 처리한번 해두면 좋을 것 같네요

2024-06-30 01:11 UTC, Arachneee commented on matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/RestaurantService.java
>                          .orElse(0.0),
기본 별점이 0.0에서 바뀌는 경우가 없을 것 같고 바로 0.0점을 확인하는 것이 더 직관적일 것 같습니다.
상수로 관리하게 되면 `기본값이 0.0이 아닐 수 있나?` 라는 생각에 코드 상단으로 다시 올라가야하는 불편함이 있을 것 같습니다.

2024-06-30 01:12 UTC, Arachneee commented on matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/RestaurantService.java
>      private RestaurantTitlesResponse toRestaurantTitlesResponse(final String githubId, Slice<Restaurant> page) {
이미 final 붙여있는 곳이 많아서 메서드 파라미터에 final을 붙이는 것이 리소스가 적을 것 같네요!
붙이는 것으로 컨벤션을 정하는 것이 좋을 것 같아요.

2024-06-30 01:15 UTC, Arachneee commented on matzip-app-external-api/src/test/java/com/woowacourse/matzip/application/RestaurantServiceTest.java
> +        }
3개 정도는 하드코딩으로 넣는 것이 훨씬 직관적으로 보이네요!

2024-07-01 04:22 UTC, PgmJun approved these changes

2024-07-04 08:35 UTC, merged