feat: 캠퍼스 식당 이름 자동완성 검색 API 구현
The-Fellowship-of-the-matzip/mat.zip-back pull request #208
Opened 2024-06-25 06:11 UTC by PgmJun

## issue: #207 

## as-is
- 

## to-be
-

2024-06-25 08:12 UTC, hyeon0208 requested changes
수고하셨습니다 이든 ~ 😀
간단한 부분들과 실수하신 부분 리뷰남기고 가니 확인해주시면 감사하겠습니다 😁
추가로 질문에 대한 의견을 아래에 남겨 놓고 갑니다 😄
---
> 조회 size 조절은 서버에서

size를 조절 가능한 위치를 정하는 건 정책에 다를 것 같다고 생각합니다
만약 사용자가 자동완성 데이터 수를 원하는 만큼 볼 수 있도록 한다면
서버에서는 이든이 말씀하신 문제를 방지하기 위해 size 제한을 걸어 둘 필요가 있어보이고
아니라면 지금 이든이 구현하신 대로 서버에서 정해진 수 만큼으로 조절해주는 것이 좋다고 생각해요😀

저는 개인적으로 자동완성으로 보여질 데이터 수를 사용자가 임의로 정할 필요는 없다고 생각해 지금이 좋은 것 같아요 😊



> 자동완성 조회 기능에 정렬이 필요할까요?

단순한 가나다 순의 정렬이라면 저 또한 정렬은 필요하지 않다고 생각해요
하지만 별점 순 또는 좋아요 수(찜 수)로 정렬되는 것은 나쁘지 않다고 생각합니다
보통 사용자가 검색을 할 때는 자신이 알아낸 인기 맛집을 가기 위해서
검색해 찾아볼 것이라고 생각하는데
위 순으로 정렬된다면 상위부터 차례로 보는 사람 특성상 자신의 원하는 맛집을
빠르게 확인할 수 있어 사용자 경험이 좀 더 좋아 질 것 같다는 의견입니다 😄

2024-06-25 08:22 UTC, PgmJun commented on matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/response/RestaurantSearchesResponse.java
> +    List<RestaurantSearchResponse> restaurants;
오 그렇네요 확인 감사합니다잉!

2024-06-25 08:57 UTC, PgmJun commented on matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/response/RestaurantSearchResponse.java
> +    public RestaurantSearchResponse() {
확인 감사합니당~~

2024-06-25 09:00 UTC, PgmJun commented on matzip-app-external-api/src/main/java/com/woowacourse/matzip/application/response/RestaurantSearchResponse.java
> +    public static RestaurantSearchResponse from(Restaurant restaurant) {
저도 final 키워드가 사용되는 곳도 있고 안된 곳도 있어서 어떻게할지 고민하다가
우선은 final 처리가 되어있는 쪽은 하고 안되어있는 쪽은 안하는 식으로 개발했는데요!

여쭤보신 부분에 대해 답변드리자면
저는 final을 선호하는 편입니다.
딱히 재할당이 필요하지 않다면 입력받은 매개변수의 재할당을 막아두어야 나중에 어디서 값이 변경되었는지 몰라 트러블슈팅에 난항을 겪는 일도 없을 것 같네요 😄
난항을 겪지 않더라도 그럴 가능성 자체를 차단항 수 있다는 점이 장점인 것 같아요~!

2024-06-25 12:15 UTC, PgmJun commented
@hyeon0208 
> 하지만 별점 순 또는 좋아요 수(찜 수)로 정렬되는 것

고민하던 부분인데 저랑 생각이 비슷하네요!
구현을 바로 하지 않고 고민한 이유는 '검색어 자동완성' 이라는 맥락 때문이었는데요
저희 서비스는 더나은 맛집을 추천하는 것이 목적인 만큼 자동완성을 통해서도 맛집 추천이 이루어지면 좋을 것 같다는 생각이 굳어졌네요 ㅎㅎ

맥락에 맞게 '검색어 자동완성'보다는 '검색어 추천'이라고 생각하고 코드의 변수나 메서드 네이밍을 조금 변경해보겠습니다.

2024-06-30 02:46 UTC, Arachneee reviewed
코드가 전체적으로 깔끔해서 보기 좋네요 👍

2024-06-30 02:46 UTC, Arachneee commented on matzip-app-external-api/src/test/java/com/woowacourse/acceptance/RestaurantAcceptanceTest.java
> +                () -> assertThat(response.as(RestaurantSearchesResponse.class).getRestaurants()).hasSize(size)
```suggestion
                () -> assertThat(response.as(RestaurantSearchesResponse.class).getRestaurants()).hasSize(size)
                .extracting("name")
                .containsExactly(names)
```

이렇게 좀 더 간결하게 표현해도 좋을 것 같아요!

2024-06-30 07:06 UTC, hyeon0208 approved these changes

2024-06-30 11:34 UTC, PgmJun commented on matzip-app-external-api/src/test/java/com/woowacourse/acceptance/RestaurantAcceptanceTest.java
> +                () -> assertThat(response.as(RestaurantSearchesResponse.class).getRestaurants()).hasSize(size)
좋은 의견 감사합니다:)
저는 그렇게 작성해도 좋지만 '사이즈가 몇 인가' 와 'names를 포함하고 있는가' 는 다른 테스트라고 생각해서 분리해두었습니다.

테스트라는 것은 물론 코드 검증 역할도 있지만, 문서의 역할도 한다고 생각해서
성능 상 문제가 발생하는 부분이 아니라면 알아보기 쉬운 코드를 선택해서 작성하는 편인데 바꾸는 것이 좋을까요??

2024-06-30 11:57 UTC, Arachneee approved these changes

2024-06-30 12:07 UTC, Arachneee commented on matzip-app-external-api/src/test/java/com/woowacourse/acceptance/RestaurantAcceptanceTest.java
> +                () -> assertThat(response.as(RestaurantSearchesResponse.class).getRestaurants()).hasSize(size)
`캠퍼스의_식당_중_입력받은_접두사로_시작하는_이름의_식당을_좋아요_기준_내림차순으로_조회한다` 테스트 코드의 방식과 통일성이 안맞아보여서 남겼습니다.

테스트하고자 하는 부분이 정확한 응답 바디를 주고 있는지 확인하는 것이기 때문에 한줄로 줄여도 알아보는데 어려움은 없을 것 같아요.

2024-06-30 12:20 UTC, PgmJun commented on matzip-app-external-api/src/test/java/com/woowacourse/acceptance/RestaurantAcceptanceTest.java
> +                () -> assertThat(response.as(RestaurantSearchesResponse.class).getRestaurants()).hasSize(size)
말씀해주셔서 다시 봤는데 그 부분은 제가 3개가 잘 오는지 개인적으로 검증하려고 코드를 써두고 지우지 못했네요!
추가로 containsAnyOf 로 값을 검증하고 있었는데 3개가 순서에 맞게 제대로 조회되어왔는 지 검사하는 것이 목적이기 때문에 containsExactly로 변경하였습니다:)

2024-07-03 12:01 UTC, merged