refactor: Restaurant 조회 시 정렬 기능 리팩토링
The-Fellowship-of-the-matzip/mat.zip-back pull request #50
Opened 2022-07-03 08:57 UTC by Ohzzi

## issue: #49

## as-is
- Spring Data Jpa 쿼리 메서드 기능으로 처리할 수 있는 기능이 `@Query`로 직접 JPQL을 작성하고 있음
- `RestaurantController`에서 불필요한 if문 사용
## to-be
- `@Formula`를 추가하여 `Restaurant` 엔티티에서 평균 별점을 정렬 조건으로 사용할 수 있도록 변경
- `Restaurant` 조회 메서드와 별점순 정렬 조회 메서드를 통합
- `RestaurantController`에서 if 분기 제거

2022-07-11 10:48 UTC, jayjaehunchoi approved these changes
오찌 if문을 없애기 위한 노력 !! 수고했삼!!

간단한 리뷰만 몇개 남깁니다~~

2022-07-11 10:48 UTC, jayjaehunchoi commented on src/main/java/com/woowacourse/matzip/domain/restaurant/RestaurantReadOnlyRepository.java
> +        boolean hasNext = restaurants.size() == pageable.getPageSize() + 1;
반복되는 `getPageSize()` 사용

2022-07-11 10:48 UTC, jayjaehunchoi commented on src/main/java/com/woowacourse/matzip/domain/restaurant/RestaurantReadOnlyRepository.java
> +        if (restaurants.size() > pageable.getPageSize()) {
```suggestion
        if (hasNext) {
```
size가 더 큰 경우는 +1 밖에 없지 않을까요?

2022-07-11 10:48 UTC, jayjaehunchoi commented on src/test/java/com/woowacourse/document/RestaurantDocumentation.java
> +        when(restaurantService.findByCampusIdAndCategoryId(eq(ORDER_BY_ID_DESC.getQuery()), eq(2L), eq(null),
`eq()`에서 코드 스멜이 난다고 하네요

2022-07-14 02:11 UTC, jinyoungchoi95 requested changes
늦어서 죄송합니다 ㅜㅜ 고생하셨습니다 :)

간단하게 생각할만한 거리들 rc남겨두었으니 확인 부탁드려요 😄

2022-07-14 02:11 UTC, jinyoungchoi95 commented on src/main/java/com/woowacourse/matzip/application/RestaurantService.java
> +                categoryId, pageable);
`query`, `page`보다는 조금 더 명확한 네이밍이면 어떨까요?

가령 `restaurantFindQuery`, `restaurants`는 어떠신가용?

2022-07-14 02:11 UTC, jinyoungchoi95 commented on src/main/java/com/woowacourse/matzip/domain/restaurant/RestaurantFindQueryFactory.java
> +                .query;
```suggestion
        return Arrays.stream(values())
                .filter(condition -> condition.key.equalsIgnoreCase(sortCondition))
                .findAny()
                .map(RestaurantFindQueryFactory::getQuery)
                .orElseThrow(InvalidSortConditionException::new);
```
개인적으로 stream 문법시에 orElseThrow가 마지막에 나오고 결과에 대한 표현이 되어야한다고 생각해요. map이라는 문법이 존재하는 이유도 이와 마찬가지이구요.
그렇다면 query보다는 현재와 같은 형태나 `map(condition -> condition.key`는 어떨까하는데 어떻게 생각하시나요?

2022-07-14 02:11 UTC, jinyoungchoi95 commented on src/main/java/com/woowacourse/matzip/domain/restaurant/RestaurantReadOnlyRepository.java
> +public class RestaurantReadOnlyRepository {
ReadOnly를 강조할 필요가 있을까요? select만을 위한 repository라면 `RestaurantFindRepository`나 `RestaurantQueryRepository`면 된다라고 생각해요.

2022-07-14 02:11 UTC, jinyoungchoi95 commented on src/main/java/com/woowacourse/matzip/domain/restaurant/RestaurantReadOnlyRepository.java
> +        boolean hasNext = restaurants.size() == pageable.getPageSize() + 1;
메소드로 분리해야하는 기능이라고 생각해요

2022-07-14 02:11 UTC, jinyoungchoi95 commented on src/main/java/com/woowacourse/matzip/domain/restaurant/RestaurantReadOnlyRepository.java
> +        int startIndex = pageable.getPageNumber() * pageable.getPageSize();
이부분도 pageable을 파라미터로 받는 calculateStartIndex 메소드로 분리해보아도 좋을 것 같아요

2022-07-14 02:11 UTC, jinyoungchoi95 commented on src/main/java/com/woowacourse/matzip/domain/restaurant/RestaurantReadOnlyRepository.java
> +                .setParameter("categoryId", categoryId)
상수로 분리하는건 어떠신가요?

2022-07-14 02:11 UTC, jinyoungchoi95 commented on src/main/java/com/woowacourse/matzip/presentation/RestaurantController.java
> +                restaurantService.findByCampusIdAndCategoryId(filterName, campusId, categoryId, pageable));
굳 ㅋㅋ

2022-07-14 02:11 UTC, jinyoungchoi95 commented on src/test/java/com/woowacourse/matzip/domain/restaurant/RestaurantReadOnlyRepositoryTest.java
> +@DataJpaTest(includeFilters = @ComponentScan.Filter(type = FilterType.ANNOTATION, classes = Repository.class))
오잉 `@DataJpaTest`가 `@Repository`를 스캔해주지않나요?

2022-07-14 02:11 UTC, jinyoungchoi95 commented on src/test/java/com/woowacourse/matzip/domain/restaurant/RestaurantReadOnlyRepositoryTest.java
> +@Import(JpaConfig.class)
반복되는부분인거같은데 차후 리팩터링 사항이 될 수 있겠네요

2022-07-14 02:11 UTC, jinyoungchoi95 commented on src/test/java/com/woowacourse/matzip/domain/restaurant/RestaurantReadOnlyRepositoryTest.java
> +class RestaurantReadOnlyRepositoryTest {
```suggestion
public class RestaurantReadOnlyRepositoryTest {
```
👀

2022-07-16 12:31 UTC, jinyoungchoi95 approved these changes

2022-07-16 12:32 UTC, merged