refactor: 인터셉터 프록시패턴 적용
The-Fellowship-of-the-matzip/mat.zip-back pull request #63
Opened 2022-08-24 08:50 UTC by jayjaehunchoi

## issue: #61 

## as-is
- 이슈에 과거 상황을 적어두었습니다.

## to-be

```java
    @Override
    public void addInterceptors(final InterceptorRegistry registry) {
        registry.addInterceptor(loginInterceptor());
    }

  
    private HandlerInterceptor loginInterceptor() {
        return new PathMatcherInterceptor(loginInterceptor)
                .excludePathPattern("/**", PathMethod.OPTIONS) // 검사하고 싶지 않은 path, pattern을 exclude합니다.
                .includePathPattern("/api/restaurants/*/reviews", PathMethod.POST); // 검사하고 싶은 경우엔 include 합니다.
    }
```

## 리뷰해주세요~

1. enum 메서드 상속

PathMethod.ANY에 대한 더 좋은 의견이 있다면 말해주세요.

```java
public enum PathMethod {
    GET,
    POST,
    PUT,
    PATCH,
    DELETE,
    OPTIONS,
    TRACE,
    HEAD,
    ANY {
        @Override
        public boolean matches(final String method) {
            return Arrays.stream(values())
                    .filter(value -> !value.equals(ANY))
                    .anyMatch(value -> value.name().equalsIgnoreCase(method));
        }
    };

    public boolean matches(final String method) {
        return name().equalsIgnoreCase(method);
    }
}
```

2022-08-24 11:06 UTC, jinyoungchoi95 requested changes
수고하셨습니다~

몇가지 코멘트 남겨두었으니 확인부탁드려요 :)

2022-08-24 11:06 UTC, jinyoungchoi95 commented on src/main/java/com/woowacourse/auth/presentation/interceptor/PathMethod.java
> +        }
하나의 의견이라고 생각해주세요 수정안하셔도 괜찮습니다. :) 

현재 `ANY`는 모든 path를 허용하고 있으므로 항상 matches에서 true를 반환하는 역할을 가지고 있어요. 다만 현재 `ANY.matches`는 matching만을 확인하는 역할이라기보다는 method를 받아서 `PathMethod`에 해당하는지 확인하는 역할도 가지고 있어요. 사실 아래에 있는 matches도 비슷하다고 볼 수 있는데요.

`String method`를 파라미터로 갖기보다는 `matches()`는 `PathMethod`를 파라미터를 가지게끔하고 `String method`는 따로 `PathMethod`로 변환하는 메소드를 제공하는게 어떻느냐라는게 제 생각입니다.
 물론 메소드가 하나가 더 늘어나기는 하지만 `matches()`가 명확하게 같은 `PathMethod`인지만 체크하는 역할만을 가짐으로써 의미가 더 명확해진다라는 생각이 있어서요 :)

String을 파라미터로 가지고 싶다면 제가말한 메소드는 기존으로 두고 아래와 같이 수정할 수 도 있구요
```java
public boolean matches(final PathMethod pathMethod) {
    return this == pathMethod;
}

public boolean matches(final String method) {
    PathMethod pathMethod = PathMethod.from(method);
    return matches(pathMethod);
}
```

2022-08-24 11:06 UTC, jinyoungchoi95 commented on src/main/java/com/woowacourse/auth/presentation/interceptor/PathMethod.java
> +        }
대신 String-> PathMethod 변환할 때 소문자를 신경써주어야겠네요 :)

2022-08-24 11:06 UTC, jinyoungchoi95 commented on src/test/java/com/woowacourse/auth/presentation/interceptor/PathContainerTest.java
> +    }
false인 경우도 테스트해볼 수 있을 것 같네요 :)

2022-08-24 11:06 UTC, jinyoungchoi95 commented on src/test/java/com/woowacourse/auth/presentation/interceptor/PathContainerTest.java
> +class PathContainerTest {
제 기억에 저희 컨벤션이 public class이었던 것 같은데 확인부탁드려요~

2022-08-25 06:28 UTC, jayjaehunchoi commented on src/test/java/com/woowacourse/auth/presentation/interceptor/PathContainerTest.java
> +class PathContainerTest {
우리 플젝이랑 헷갈렸네연 ㅎㅋ

2022-08-25 06:37 UTC, Ohzzi approved these changes
수고 많으셨습니다! 메서드나 변수 명 관련해서 간단한 리뷰 남겼어요!

2022-08-25 06:37 UTC, Ohzzi commented on src/main/java/com/woowacourse/auth/presentation/interceptor/PathContainer.java
> +                .anyMatch(requestPath -> anyMatchPathPattern(targetPath, pathMethod, requestPath));
```suggestion
    public boolean isNotIncludedPath(final String targetPath, final String pathMethod) {
        boolean isExcludePattern = excludePathPatterns.stream()
                .anyMatch(requestPath -> anyMatchPathPattern(targetPath, pathMethod, requestPath));

        boolean isIncludePattern = includePathPatterns.stream()
                .anyMatch(requestPath -> anyMatchPathPattern(targetPath, pathMethod, requestPath));
```

2022-08-25 06:37 UTC, Ohzzi commented on src/main/java/com/woowacourse/auth/presentation/interceptor/PathContainer.java
> +    }
```suggestion
    public void addIncludePathPattern(final String targetPath, final PathMethod pathMethod) {
        this.includePathPatterns.add(new RequestPathPattern(targetPath, pathMethod));
    }

    public void addExcludePathPattern(String targetPath, PathMethod pathMethod) {
        this.excludePathPatterns.add(new RequestPathPattern(targetPath, pathMethod));
    }
```
`includePathPattern`과 `excludePathPattern`을 추가해준다는 의미가 명확히 들어가는게 좋을 것 같네요

2022-08-25 06:37 UTC, Ohzzi commented on src/main/java/com/woowacourse/auth/presentation/interceptor/PathMethod.java
> +                    .filter(value -> !value.equals(ANY))
여기는 enum끼리 비교니까 `==` 써도 될 것 같아요!

2022-08-25 06:37 UTC, Ohzzi commented on src/main/java/com/woowacourse/auth/presentation/interceptor/PathMethod.java
> +}
저는 그냥 String으로 받아도 괜찮겠다는 입장입니다!

2022-08-25 06:58 UTC, jayjaehunchoi commented on src/main/java/com/woowacourse/auth/presentation/interceptor/PathMethod.java
> +        }
좋은 의견인것 같은데여? 하지만 반영은 보류해보겠습니다. 보류하는 이유는 ...........

2022-08-25 07:18 UTC, jinyoungchoi95 commented on src/main/java/com/woowacourse/auth/presentation/interceptor/PathMethod.java
> +        }
킹받네....

2022-08-25 07:31 UTC, jinyoungchoi95 approved these changes

2022-08-25 07:31 UTC, merged