refactor: 리뷰 조회시 본인이 작성자인지 반환한다.
The-Fellowship-of-the-matzip/mat.zip-back pull request #67
Opened 2022-08-25 09:13 UTC by jayjaehunchoi

## issue: #60 

## as-is
- 본인이 작성자인지 몰라 수정이 불가합니다.

## to-be

```java

    @Override
    public void addInterceptors(final InterceptorRegistry registry) {
        registry.addInterceptor(loginOrNotInterceptor());
        registry.addInterceptor(loginInterceptor());
    }

    private HandlerInterceptor loginInterceptor() {
        return new PathMatcherInterceptor(loginInterceptor)
                .excludePathPattern("/**", PathMethod.OPTIONS) // 생각해보니까 이거 자체가 필요 없겠군요 (지금은)
                .includePathPattern("/api/restaurants/*/reviews", PathMethod.POST);
    }

  // loginInterceptor를 훼손시키지 않고 싶어서.. 이런 선택을 했음다.. 어떻게 구현하면 베스트일까용
    private HandlerInterceptor loginOrNotInterceptor() {
        return new PathMatcherInterceptor(notLoginInterceptor)
                .includePathPattern("/api/restaurants/*/reviews", PathMethod.GET);
    }

```

2022-08-27 04:01 UTC, jinyoungchoi95 approved these changes
수고하셨습니다~

의견 몇가지만 남겨두었으니 확인부탁드려요 :)

2022-08-27 04:01 UTC, jinyoungchoi95 commented on core/src/main/java/com/woowacourse/matzip/domain/review/Review.java
> +    }
`githubId`같은 경우 null한 값이 들어올 수 있는 상태에요. null이 보통은 불가능하도록 검증을 두긴하지만 현재는 nullable하도록 둔다라면 `final @Nullable String githubId`로 두어서 nullable함을 명시하는게 어떨까 싶네요.

한편으로는 githubId가 nullable하게 들어온다라면 `AuthenticationContext`에서 `getContext`가 가져다 주는 값이 nullable하다라는 것이 되므로 `getContext`에서 Optional 하게 반환하는 건 어떨까요?
(기존의 AuthenticationContext는 null이 불가능한 구조이니 Context를 두개로 두게 될 수도 있겠네요)

2022-08-27 04:01 UTC, jinyoungchoi95 commented on app-external-api/src/main/java/com/woowacourse/auth/config/AuthConfig.java
> +        this.notLoginInterceptor = new NotLoginInterceptor(loginInterceptor);
이거 notLoginInterceptor를 그대로 받아와도 될 것같은데 이렇게 짠 이유가 있을까요?

2022-08-27 04:22 UTC, jayjaehunchoi commented on app-external-api/src/main/java/com/woowacourse/matzip/application/response/ReviewResponse.java
> +        this.updatable = updatable;
dto 반환 값이 writer일 때 docs 만드는 지점에서 문제가 생기더라구요 그래서 이렇게 바꿨어요. isWriter 쪽을 updatable로 변경하겠습니다.

2022-08-27 04:24 UTC, jayjaehunchoi commented on app-external-api/src/main/java/com/woowacourse/auth/config/AuthConfig.java
> +        this.notLoginInterceptor = new NotLoginInterceptor(loginInterceptor);
pathMatcher를 사용하기 위해 HandlerInterceptor를 상속 받았어요 이것도 수정할 방법이 떠올라서 한 번 시도해보겠습니다.

2022-08-27 04:37 UTC, jayjaehunchoi commented on app-external-api/src/main/java/com/woowacourse/auth/config/AuthConfig.java
> +        this.notLoginInterceptor = new NotLoginInterceptor(loginInterceptor);
수정 불가능 해보이네연.. ㅋㅋㅋ 이대로 유지해야 할 것 같슴다

2022-08-27 04:44 UTC, jayjaehunchoi commented on core/src/main/java/com/woowacourse/matzip/domain/review/Review.java
> +    }
> githubId같은 경우 null한 값이 들어올 수 있는 상태에요. null이 보통은 불가능하도록 검증을 두긴하지만 현재는 nullable하도록 둔다라면 final @Nullable String githubId로 두어서 nullable함을 명시하는게 어떨까 싶네요.

동의합니다. 더불어 해당 코드에 대해서는 null에 대해 조금 더 주의깊게 사용할 수 있겠네요

> 한편으로는 githubId가 nullable하게 들어온다라면 AuthenticationContext에서 getContext가 가져다 주는 값이 nullable하다라는 것이 되므로 getContext에서 Optional 하게 반환하는 건 어떨까요?
(기존의 AuthenticationContext는 null이 불가능한 구조이니 Context를 두개로 두게 될 수도 있겠네요)

LoginInterceptor와 관련 코드들(ArgumentResolver, AuthenticationContext)을 재사용 하여 notLogin도 확인하고 있어서 하나를 분리하게 되면 NotLoginInterceptor만을 위한 모든 도우미 코드가 다시 생성되어야 할 것 같습니다. (이 방법도 괜찮아 보이네여)

현재 상태에서 Optional로만 변경하는 것은 결국 null을 뱉기위해 한단계 더 코드를 작성하는 것 뿐이라는 생각이 들어요. Optional은 null을 우아하게 처리하기 위함인데 결국 null을 반환하는 현재 구조라면 지금 상태 유지하고 첫 단락의 피드백을 반영해서 null을 주의하는 코드를 작성하는 게 괜찮아 보이는데 어떠신지요. 

이번 기능(수정, 삭제)이 끝나면 위에서 언급한대로 도우미 코드를 새로 쭉 생성하여 not login or login 지점에만 적용할 수 있는 코드로 분리해보겠습니다.

2022-08-27 04:46 UTC, jayjaehunchoi commented on core/src/main/java/com/woowacourse/matzip/domain/review/Review.java
> +    }
아 지금막 하나의 방법이 떠올라서 일단 시도해볼게연 이것부터

2022-08-28 07:24 UTC, Ohzzi requested changes
수고하셨습니다 후니! 인터셉터끼리의 구조 관련해서만 리뷰를 남겼습니다! 확인 부탁드려요

2022-08-28 07:24 UTC, Ohzzi commented on app-external-api/src/main/java/com/woowacourse/auth/presentation/interceptor/NotLoginInterceptor.java
> +    private final AuthenticationContext authenticationContext;
그리고 결국 `NotLoginInterceptor`가 `LoginInterceptor`를 쓰게 된다면 클래스 명도 바뀌어야 할 것 같네요

2022-08-29 04:54 UTC, jayjaehunchoi commented on app-external-api/src/main/java/com/woowacourse/auth/presentation/interceptor/NotLoginInterceptor.java
> +    private final AuthenticationContext authenticationContext;
두 클래스 모두 HandlerInterceptor를 상속받는거라 빈으로 등록하는 것 자체가 불가능 하네요 ㅠㅠ

2022-08-29 04:59 UTC, jayjaehunchoi commented on app-external-api/src/main/java/com/woowacourse/auth/config/AuthConfig.java
> +        this.notLoginInterceptor = new NotLoginInterceptor(loginInterceptor);
구체 클래스 사용하는 걸로 변경해서 수정했어용

2022-08-30 03:09 UTC, Ohzzi approved these changes

2022-08-30 03:10 UTC, merged