feat: 캠퍼스 entity 구현
The-Fellowship-of-the-matzip/mat.zip-back pull request #7
Opened 2022-06-02 08:30 UTC by Ohzzi

## issue: #6

## as-is
- Campus entity 미구현

## to-do
- Campus entity 구현
  - Campus entity와 CampusRepository 구현
- Campus entity의 이름 column은 `enum`으로 관리
```java
@Getter
public enum CampusName {

    JAMSIL("잠실"),
    SEOLLEUNG("선릉"),
    ;

    private final String value;

    CampusName(final String value) {
        this.value = value;
    }

    public static CampusName from(final String value) {
        return Arrays.stream(values())
                .filter(campusName -> campusName.getValue().equals(value))
                .findAny()
                .orElseThrow(() -> new IllegalArgumentException("존재하지 않는 캠퍼스 이름입니다."));
    }
}
```

2022-06-04 10:31 UTC, jayjaehunchoi requested changes
오찌 굳~~ 
리뷰 남겨요~ 리뷰 남길내용이 거의 없지만 우리끼리 뭔가 정하고 넘어가면 좋을만한 주제들에 대해 리뷰 남깁니다.

2022-06-04 10:31 UTC, jayjaehunchoi commented on src/test/java/com/woowacourse/matzip/domain/campus/CampusTest.java
> +    }
동등성 비교에 대한 테스트는 빼기로 했어용~~

2022-06-04 10:31 UTC, jayjaehunchoi commented on src/test/java/com/woowacourse/matzip/domain/campus/CampusTest.java
> +class CampusTest {
```suggestion
public class CampusTest {
```

다른 테스트들과의 컨벤션을 맞추는게 좋을거같아영

2022-06-04 10:31 UTC, jayjaehunchoi commented on src/main/java/com/woowacourse/matzip/domain/campus/CampusName.java
> +                .filter(campusName -> campusName.getValue().equals(value))
```suggestion
                .filter(campusName -> value.equals(campusName.value))
```

이렇게 수정하는 것은 어떠신지요

2022-06-04 10:31 UTC, jayjaehunchoi commented on src/main/java/com/woowacourse/matzip/domain/campus/Campus.java
> +    @Override
동등성 비교 대상을 어디까지 가져갈 것인지에 대해 담에 이야기를 한 번 나눠봅시다

2022-06-05 00:12 UTC, jinyoungchoi95 approved these changes
조금 늦은 리뷰 죄송합니다 ㅜㅜ

후니가 잡아야할부분 다 챙겨주셔서 저는 approve 남겨두겠습니당 :)
동등성관련된 부분만 평일중에 얘기하는걸로해요!

2022-06-05 00:12 UTC, jinyoungchoi95 commented on src/main/java/com/woowacourse/matzip/domain/campus/Campus.java
> +    @Column(unique = true)
저도 이거 안해두긴해서 다음 pr때 수정해야할 내용인데요.
column의 테이블명은 명시하는거에 대해서 어떻게 생각하시나요?

2022-06-09 06:45 UTC, jayjaehunchoi approved these changes

2022-06-09 06:45 UTC, merged