feat: 리뷰 수정, 삭제 api를 구현한다.
The-Fellowship-of-the-matzip/mat.zip-back pull request #73
Opened 2022-08-30 06:31 UTC by jayjaehunchoi

## issue: #62 

## as-is
- 리뷰 수정, 삭제 api가 없음

## to-be
`PUT /api/restaurants/{restaurantId}/reviews/{reviewId}`
content: String
rating: NUMBER
menu: String

`DELETE /api/restaurants/{restaurantId}/reviews/{reviewId}`

### 건의 사항

현재 deleteReview 코드가 절차적으로 작성되어 있습니다.
삭제라는 도메인 로직을 응용 레이어에서 갖고 있어요. 이런 경우 저는 도메인에 delete 메서드를 만들고 delete를 실행할 수 있는 [도메인 서비스](https://www.manty.co.kr/bbs/detail/develop?id=146) 를 만들어 사용하는 편입니다. 하지만 현재 멀티 모듈 구조상 repository를 api 모듈에서 참조하면 도메인에 해당 도메인 서비스를 넣을 수 없고(의존성이 api -> core 이기 때문) 도메인 서비스가 코어에 있을 경우 repository를 참조할 수 가 없습니다.

따라서 핵심이 되는 Repository는 core로 이동하여 도메인 서비스를 만들 수 있도록 하면 응용 계층에서의 도메인 지식을 제거할 수 있을 것 같습니다.

2022-08-31 00:36 UTC, Ohzzi requested changes
후니 수고하셨습니다~ 같이 생각해 볼 부분이 있어서 RC 날릴게요

2022-08-31 00:36 UTC, Ohzzi commented on app-external-api/src/main/java/com/woowacourse/matzip/application/ReviewService.java
> +                .orElseThrow(MemberNotFoundException::new);
`review.update`에서 깃허브 아이디만 쓸거라면 그냥 exists 쿼리를 날리는 쪽이 더 낫지 않을까요?
아니면 update가 member를 받고 equals로 작성자 비교를 해도 될 것 같아요

2022-08-31 00:36 UTC, Ohzzi commented on app-external-api/src/main/java/com/woowacourse/matzip/application/ReviewService.java
> +        }
이 부분은 `delete` 내의 부가적인 기능이니 메서드 분리하는게 어떨까요

2022-08-31 00:36 UTC, Ohzzi commented on app-external-api/src/main/java/com/woowacourse/matzip/application/ReviewService.java
> +                .orElseThrow(MemberNotFoundException::new);
하나 더 의견을 내자면, 어차피 리뷰 안에서 깃허브 아이디로 작성자인지 검증하고 있다면, 굳이 로그인한 회원을 조회해 올 필요가 없지 않을까요? 만약 토큰이 위/변조 되어서 이상한 깃허브 아이디가 들어왔다면 어차피 리뷰의 작성자가 아니라고 판단이 될테니까요

2022-08-31 00:36 UTC, Ohzzi commented on app-external-api/src/main/java/com/woowacourse/support/exception/GlobalControllerAdvice.java
> +            ReviewNotFoundException.class
NotFound들의 상위 예외를 만들어서 한번에 잡는건 어떨까요

2022-08-31 00:45 UTC, jayjaehunchoi commented on app-external-api/src/main/java/com/woowacourse/matzip/application/ReviewService.java
> +                .orElseThrow(MemberNotFoundException::new);
https://techblog.woowahan.com/2645/

제가 참고한 글입니다.

2022-08-31 00:46 UTC, jayjaehunchoi commented on app-external-api/src/main/java/com/woowacourse/support/exception/GlobalControllerAdvice.java
> +            ReviewNotFoundException.class
후우 이거 고치는 사람 내가 되었군,,..

2022-08-31 00:46 UTC, jayjaehunchoi commented on app-external-api/src/main/java/com/woowacourse/matzip/application/ReviewService.java
> +                .orElseThrow(MemberNotFoundException::new);
> review.update에서 깃허브 아이디만 쓸거라면 그냥 exists 쿼리를 날리는 쪽이 더 낫지 않을까요?
아니면 update가 member를 받고 equals로 작성자 비교를 해도 될 것 같아요

이 의견도 좋네요

2022-08-31 04:57 UTC, Ohzzi commented on app-external-api/src/main/java/com/woowacourse/matzip/application/ReviewService.java
> +                .orElseThrow(MemberNotFoundException::new);
>https://techblog.woowahan.com/2645/

네 저도 이 의견에는 공감합니다. 그러나 여기에서 제가 말씀드리려고 한 것과는 살짝 차이가 있는데요, 예를 들어 리뷰 작성의 경우 넘어온 회원 아이디가 진짜 있는 회원인지 확인하기 위해 select를 해오는 것이 맞다고 생각합니다. 서비스 입장에서는 보장이 안되어 있으니까요. 하지만 update의 경우 어차피 넘어온 값이 리뷰가 담고 있는 실제 회원 아이디 값과 다르다면 검증 과정에서 false를 반환하고 예외를 터뜨릴 것이기 때문에, select 과정이 굳이 의미가 없을 것 같다는 의견이었습니다.

예를 들어 리뷰를 작성한 회원 깃허브 아이디가 "huni"일 때, 토큰이 위변조 되어 "asdf"라는 값이 넘어오면 "asdf"라는 회원이 있든 말든 상관 없이 어차피 리뷰 작성자 검증에서 "huni"와 다르기 때문에 예외를 반환해 줄 것이기 때문이죠.

물론 이것은 하나의 의견일 뿐입니다!

2022-08-31 04:57 UTC, Ohzzi commented on app-external-api/src/main/java/com/woowacourse/support/exception/GlobalControllerAdvice.java
> +            ReviewNotFoundException.class
딱걸렸어~

2022-09-03 07:38 UTC, jayjaehunchoi commented on app-external-api/src/main/java/com/woowacourse/matzip/application/ReviewService.java
> +                .orElseThrow(MemberNotFoundException::new);
일단 머지 ㄱ

2022-09-03 08:20 UTC, Ohzzi approved these changes

2022-09-03 08:25 UTC, merged