feat: 식당 추가 요청 관련 API 구현
The-Fellowship-of-the-matzip/mat.zip-back pull request #78
Opened 2022-09-12 03:34 UTC by Ohzzi

## issue: closes #76 

## as-is
- 식당 추가 요청에 대한 CRUD 미구현

## to-be
- 식당 추가 요청에 대한 CRUD 구현

2022-09-13 04:10 UTC, jayjaehunchoi requested changes
전반적으로 좋은데, RestaurantRequest controller url 부분을 다시 고민해보면 좋을것 같으!

2022-09-13 04:10 UTC, jayjaehunchoi commented on app-external-api/src/main/java/com/woowacourse/matzip/domain/restaurant/RestaurantRequestRepository.java
> +    @EntityGraph(attributePaths = {"member"}, type = EntityGraphType.FETCH)
엔티티 명시 타입을 따르도록 LOAD 타입으로 해도 괜찮을듯 (어차피 다 Lazy 겠지만) 안바꿔도 상관 x

2022-09-13 04:10 UTC, jayjaehunchoi commented on app-external-api/src/main/java/com/woowacourse/matzip/presentation/RestaurantRequestController.java
> +@RequestMapping("/api/campuses/{campusId}/restaurants/requests")
url로 받는 것보다  요청값으로 전달받는게 낫지 않을ㄹ까 싶은데. 레스토랑 생성 요청이 캠퍼스와 레스토랑의 하위 리소스라는 생각이 잘 안드넹

2022-09-13 04:26 UTC, jinyoungchoi95 requested changes
고생하셨습니다 오찌 :)

같이 생각하면 좋을만한 부분들 코맨트 드려요 🙇‍♂️

2022-09-13 04:26 UTC, jinyoungchoi95 commented on app-external-api/src/main/java/com/woowacourse/auth/config/AuthConfig.java
> +    private static final String RESTAURANT_REQUESTS_PATH = "/api/campuses/*/restaurants/requests";
`/api/campuses/*/restaurant_requests`가 조금 더 자연스럽지 않을까요?
현재 구현되어있는 구조에서는 request가 restaurant의 하위도메인이라는 생각이 덜드는것 같아요

2022-09-13 04:26 UTC, jinyoungchoi95 commented on app-external-api/src/main/java/com/woowacourse/matzip/application/RestaurantRequestService.java
> +        Member member = memberRepository.findMemberByGithubId(githubId).orElseThrow(MemberNotFoundException::new);
```suggestion
        Member member = memberRepository.findMemberByGithubId(githubId)
            .orElseThrow(MemberNotFoundException::new);
```

2022-09-13 04:26 UTC, jinyoungchoi95 commented on app-external-api/src/main/java/com/woowacourse/matzip/application/RestaurantRequestService.java
> +        return new RestaurantRequestsResponse(restaurantRequests, page.hasNext());
저희 이거 dto 변환은 정적 팩토리 메소드 사용하기로 되어있지 않았나용?

2022-09-13 04:26 UTC, jinyoungchoi95 commented on app-external-api/src/main/java/com/woowacourse/matzip/application/RestaurantRequestService.java
> +        return new RestaurantRequestsResponse(restaurantRequests, page.hasNext());
일련의 과정들이 Response에서 진행되어도 되지 않을까요?

2022-09-13 04:26 UTC, jinyoungchoi95 commented on app-external-api/src/main/java/com/woowacourse/matzip/application/response/RestaurantRequestResponse.java
> +        String authorGithubId = restaurantRequest.getMember().getGithubId();
```suggestion
        String authorGithubId = restaurantRequest.getMember()
            .getGithubId();
```
사소한 객체지향 생활 체조 원칙 😆

2022-09-13 04:26 UTC, jinyoungchoi95 commented on app-external-api/src/test/java/com/woowacourse/matzip/application/RestaurantRequestServiceTest.java
> +    void 없는_유저가_요청할_경우_예외_발생() {
무엇을 요청한지 들어가면 좋을 것 같아요 😄

2022-09-13 04:26 UTC, jinyoungchoi95 commented on app-external-api/src/main/java/com/woowacourse/matzip/application/RestaurantRequestService.java
> +    }
이 부분도 `RestaurantRequest`내부에서 동작하면 어떨까요? 해당 객체가 지녀야할 비즈니스 로직처럼보이네요

2022-09-13 04:26 UTC, jinyoungchoi95 commented on core/src/main/java/com/woowacourse/matzip/domain/restaurant/RestaurantRequest.java
>  public class RestaurantRequest {
요거 저번 리뷰를 못해드려서 이제 확인한 것 같아요.

`Request`가 저희가 dto에서 요청값으로 사용하는 부분이다보니 조금 헷갈리는 경향이 없지않아 있는 것 같아요. 다른 네이밍으로 바꾸어야하지않나라는 생각이 드는데 어떻게 생각하세요?

2022-09-13 04:51 UTC, Ohzzi commented on app-external-api/src/main/java/com/woowacourse/matzip/presentation/RestaurantRequestController.java
> +@RequestMapping("/api/campuses/{campusId}/restaurants/requests")
이거 사실 통일성을 이렇게 해서 이렇게 한 부분... 전체적으로 URL을 다 뜯어고칠 필요가 있어 보임

2022-09-13 04:52 UTC, Ohzzi commented on app-external-api/src/main/java/com/woowacourse/auth/config/AuthConfig.java
> +    private static final String RESTAURANT_REQUESTS_PATH = "/api/campuses/*/restaurants/requests";
URL 부분은 프론트와도 상의해야 할 부분이라서 이야기 한 번 해볼게여

2022-09-13 04:53 UTC, Ohzzi commented on core/src/main/java/com/woowacourse/matzip/domain/restaurant/RestaurantRequest.java
>  public class RestaurantRequest {
프론트와도 모아서 이야기를 해봐야겠네요

2022-09-14 08:30 UTC, Ohzzi commented
추가로 아직 API상으로 식당 추가 요청에 대해 식당 등록을 시키는 API가 없어서(그건 어드민이므로) 이미 등록된 식당에 대한 추가 요청 수정/삭제 인수 테스트가 존재하지 않음. 나중에 추가 해야 함.

2022-09-15 03:01 UTC, jinyoungchoi95 approved these changes
LGTM 👍

2022-09-15 03:01 UTC, jinyoungchoi95 commented on app-external-api/src/main/java/com/woowacourse/matzip/presentation/RestaurantDemandController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
이거 제발 빌더 제공해주세요 스프링님....

2022-09-15 04:07 UTC, jayjaehunchoi approved these changes

2022-09-15 04:09 UTC, merged